row_scout_config:
  # Location Settings
  location:
    # The DRAM bank to be profiled.
    bank: 1
    # Inclusive range of DRAM row addresses to be profiled.
    range: [12, 15]

  # Profiling Group Specifications
  group:
    # Layout of rows in a row group indicating the distance between rows. For instance, "R-R-R"
    # suggests three rows where each 'R' represents a retention-profiled row and '-' indicates a
    # distance of one DRAM row.
    layout: "R-R-R"
    # Specifies the number of row groups to find.
    amount: 1

  # Retention Time Management
  retention:
    # Initial retention time in milliseconds for the profiling process. This is the starting point for testing
    # DRAM rows to determine if they can retain data correctly over this duration without any errors.
    initial_ms: 100

    # Increment in milliseconds to adjust the retention time when the initially profiled rows do not meet
    # the specified criteria for retention consistency.
    increment_ms: 50

    # Number of validation cycles to perform for each row in a candidate row group to ensure that the retention
    # time is consistently reliable across multiple tests. This process is critical to counteract the effects of
    # Variable Retention Time (VRT), a phenomenon where the retention time of DRAM cells changes unpredictably
    # over time.
    validation_cycles_count: 1000

  # Data Initialization Pattern
  data:
    # Specifies the pattern used to initialize data in DRAM rows for profiling. Options are:
    # 0 - random, 1 - all ones, 2 - all zeros, 3 - colstripe (0101), 4 - inverse colstripe (1010),
    # 5 - checkered (0101, 1010), 6 - inverse checkered (1010, 0101). Each pattern serves to test
    # different data retention scenarios.
    pattern: 0

  # Mapping Scheme for DRAM rows
  mapping_scheme:
    # Defines how logical row IDs are converted to physical row IDs and vice versa.
    # 0 - Sequential mapping (default), 1 - Samsung chip typical mapping scheme.
    # This setting is crucial for systems where the physical and logical mapping of memory rows
    # affects performance and profiling accuracy.
    scheme: 0
